// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list_recent_entries.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_entries_default = defineTool({
  name: "list_recent_entries",
  title: "List recent casino entries",
  description: "List the signed-in user's most recent casino profit entries (dashboard history).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many entries to return."),
    account: z.enum(["Ruan", "Rita"]).optional().describe("Filter by account (Ruan or Rita)."),
    house: z.string().optional().describe("Filter by casino/house name.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, account, house }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("casino_entries").select("*").order("created_at", { ascending: false }).limit(limit);
    if (account) q = q.eq("account", account);
    if (house) q = q.ilike("house", house);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create_entry.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_entry_default = defineTool2({
  name: "create_entry",
  title: "Create casino entry",
  description: "Create a new profit/loss entry in the signed-in user's dashboard.",
  inputSchema: {
    amount: z2.number().describe("Profit (positive) or loss (negative) amount."),
    type: z2.string().describe("Entry type (e.g. bonus, giros, apostas, missao, aposte_ganhe)."),
    house: z2.string().min(1).describe("Casino/house name."),
    game: z2.string().min(1).describe("Game name."),
    account: z2.enum(["Ruan", "Rita"]).default("Ruan"),
    notes: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ amount, type, house, game, account, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("casino_entries").insert({ amount, type, house, game, account, notes: notes ?? null, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created entry ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/month_summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var month_summary_default = defineTool3({
  name: "month_summary",
  title: "Month summary",
  description: "Summarize the signed-in user's profits for a given month (default: current month, Bras\xEDlia time).",
  inputSchema: {
    year: z3.number().int().min(2020).max(2100).optional(),
    month: z3.number().int().min(1).max(12).optional().describe("1-12")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ year, month }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const now = /* @__PURE__ */ new Date();
    const y = year ?? now.getUTCFullYear();
    const m = month ?? now.getUTCMonth() + 1;
    const start = `${y}-${String(m).padStart(2, "0")}-01T03:00:00Z`;
    const nextY = m === 12 ? y + 1 : y;
    const nextM = m === 12 ? 1 : m + 1;
    const end = `${nextY}-${String(nextM).padStart(2, "0")}-01T03:00:00Z`;
    const { data, error } = await sb3(ctx).from("casino_entries").select("amount, account, house, game, type, created_at").gte("created_at", start).lt("created_at", end);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total = rows.reduce((s, r) => s + Number(r.amount), 0);
    const byAccount = {};
    const byHouse = {};
    for (const r of rows) {
      byAccount[r.account] = (byAccount[r.account] ?? 0) + Number(r.amount);
      byHouse[r.house] = (byHouse[r.house] ?? 0) + Number(r.amount);
    }
    const summary = { year: y, month: m, total, count: rows.length, byAccount, byHouse };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list_daily_tasks.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function todayBrasilia() {
  const now = /* @__PURE__ */ new Date();
  const brt = new Date(now.getTime() - 3 * 60 * 60 * 1e3);
  return brt.toISOString().slice(0, 10);
}
var list_daily_tasks_default = defineTool4({
  name: "list_daily_tasks",
  title: "List daily tasks",
  description: "List today's daily tasks for the signed-in user with completion status per account (Bras\xEDlia timezone).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb4(ctx);
    const today = todayBrasilia();
    const [tasks, done] = await Promise.all([
      client.from("daily_tasks").select("*").order("created_at"),
      client.from("daily_task_completions").select("*").eq("completion_date", today)
    ]);
    if (tasks.error) return { content: [{ type: "text", text: tasks.error.message }], isError: true };
    if (done.error) return { content: [{ type: "text", text: done.error.message }], isError: true };
    const completions = done.data ?? [];
    const result = (tasks.data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      house: t.house,
      description: t.description,
      accounts: t.accounts,
      completedBy: completions.filter((c) => c.task_id === t.id).map((c) => c.account)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ date: today, tasks: result }, null, 2) }],
      structuredContent: { date: today, tasks: result }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bkscfulrsocwdwckgzgw";
var mcp_default = defineMcp({
  name: "casino-tracker-mcp",
  title: "Casino Tracker MCP",
  version: "0.1.0",
  instructions: "Tools for the signed-in user's Casino Tracker data: list recent profit entries, create new entries, summarize the month, and inspect daily tasks. All tools act as the authenticated user via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_entries_default, create_entry_default, month_summary_default, list_daily_tasks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
